DROP TABLE IF EXISTS book;

CREATE TABLE IF NOT EXISTS book
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL,
    author VARCHAR(100) NOT NULL,
    releaseYear INT NOT NULL
);

SELECT * FROM book;

INSERT INTO book (name, author, releaseYear)
VALUES
    ('1984', 'Джордж Оруэлл', '1949'),
    ('Гарри Поттер и философский камень', 'Джоан Роулинг', '1997'),
    ('Великий Гэтсби', 'Фицджеральд, Фрэнсис Скотт', '1925'),
    ('Убить пересмешника', 'Харпер Ли', '1960'),
    ('Властелин колец: Братство кольца', 'Дж. Р.. Толкин', '1954');